source 'https://github.com/CocoaPods/Specs.git'

target 'InputHandler', :exclusive => true do
  pod "InputHandler", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "InputHandler", :path => "../"

  
end
